/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/controladores': RouteRecordInfo<'/controladores', '/controladores', Record<never, never>, Record<never, never>>,
    '/empresas': RouteRecordInfo<'/empresas', '/empresas', Record<never, never>, Record<never, never>>,
    '/entradas': RouteRecordInfo<'/entradas', '/entradas', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/pessoas': RouteRecordInfo<'/pessoas', '/pessoas', Record<never, never>, Record<never, never>>,
    '/saidas': RouteRecordInfo<'/saidas', '/saidas', Record<never, never>, Record<never, never>>,
    '/veiculos': RouteRecordInfo<'/veiculos', '/veiculos', Record<never, never>, Record<never, never>>,
  }
}
